POST http://127.0.0.1:5000/polynomial
Content-Type: application/json

{
    "poly1":"+4x^2y^3 ( +7x )(6x) -3xy^5* ( +1x^5 +5x -1 )",
    "poly2":"+4x^3 -3x^2 -2x +4",
    "choice":2,
    "answer":""
}